### ISSUE TITLE
Issue outputing vtk

### ISSUE THREAD

**Issue by hynny** [UG4/plugin_Limex#1] opened 2021-02-23 19:31 UTC
VTk observer fails to output vtk files except for the initial values. An old version of Limex once could be used to avoid this issue. However, up-to-date ugcore requires the latest Limex, I guess it is since some interfaces were moved to ugcore.

**Comment by anaegel** [comment] 2021-02-23 19:55
As you pointed out, ITimeIntegratorObserver<TDomain, TAlgebra>, which is the base class of VTKOutputObserver, has been moved to ugcore. We tried to leave the LUA-API unchanged, but you need to update both ugcore and plugin_Limex. Can you provide a minimal (non-)working example or error logs? Thanks! (@timsschoen: FYI)

**Comment by hynny** [comment] 2021-02-23 20:23
Thank you for the reply.

The simulation ran successfully without any error when ugcore and Limex both are up-to-date.  The vtk outputs are as follow,

> solution_p00_s0_t0000.vtu
> solution_p00_s1_t0000.vtu
> solution_p00_s2_t0000.vtu
> solution_p00_s3_t0000.vtu
> solution_p01_s0_t0000.vtu
> solution_p01_s1_t0000.vtu
> solution_p01_s2_t0000.vtu
> solution_p01_s3_t0000.vtu
> solution.pvd
> solution_s0_t0000.pvtu
> solution_s1_t0000.pvtu
> solution_s2_t0000.pvtu
> solution_s3_t0000.pvtu
> solution_t0000.pvd


If an old version of Limex is used(I used 1384a90d0d1f75f582563e71cdf4295f17bfd474), I got the following error message:

> ERRORS OCCURED:
> #### Registry ERROR (ITimeIntegratorObserver2dCPU1):Trying to register class name 'ITimeIntegratorObserver2dCPU1', that is already used by another class in this registry.
> ### ERROR while registering functionality at 'ug4//Limex'. Registration failed (using name ITimeIntegratorObserver2dCPU1).
> UGError occurred during plugin initialization:
> /home/tuf85324/ug4/ugcore/cmake/../../ugcore/ugbase/registry/registry_impl.h:178 : Trying to register class name 'ITimeIntegratorObserver2dCPU1', that is already used by another class in this registry.

**Comment by bsumirak** [comment] 2021-02-24 02:13
The problem is due not to the relocation of functionality to ugcore, but to commit 55d163f, which changed the interface ITimeIntegratorObserver. The new step_postprocess method does no longer provide a previous solution grid function, so the VTK observer can no longer interpolate in-between steps.
Could this be fixed by saving the pointer to the current solution grid function in VTKOutputObserver and using it as previous solution in the next step?

**Comment by anaegel** [comment] 2021-02-24 07:43
Thanks - yes, that's true: Indeed, we removed the old solution from the **function interface**,  as we wanted to match the interface of the existing time integrators (for both LUA and C).  However, equivalent functionality can still be provided within the **TimeIntegratorSubject** interface, which implements an observer design-pattern. Using this mechanism, we can implement, what @bsumirak suggested. Stepping from $t_0$ to $t_0+\tau$, one can use **TimeIntegratorSubject::notify_init_step** to save the solution at time $t_0$. **TimeIntegratorSubject::notifiy_finalize_step** is supposed to be called after a successful step at $t_0+\tau$.

**Comment by bsumirak** [comment] 2021-02-24 07:47
Ah, perfect, thanks.
I think I will find the time to implement this as you suggested.

**Comment by anaegel** [comment] 2021-02-24 07:50
Thanks! As an additional note: You may want to look into 
ugbase/lib_disc/time_disc/time_integrator_subject.hpp
ugbase/lib_disc/time_disc/time_integrator_observers/lua_callback_observer.hpp
from commit b39ec6f4b53776de3c0442693d465569866fb47, which can provide additional guidance!

**Comment by stephanmg** [comment] 2021-04-07 10:50
Is this now resolved and can be merged? If so, somebody should merge it. (I can't).

**Comment by bsumirak** [comment] 2021-11-02 22:25
merged and closed

**Closed as completed by bsumirak** 2021-11-02 22:25 UTC
